version: "3.2"

services:
  db:
    image: mariadb:10.2
    container_name: matomo_db
    volumes:
      - "db:/var/lib/mysql"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=matomo"
      - "MYSQL_USER=matomo"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  redis:
    image: redis:4.0-alpine
    container_name: matomo_redis
    restart: always

  matomo:
    image: crazymax/matomo:latest
    container_name: matomo
    depends_on:
      - db
      - redis
    ports:
      - target: 8000
        published: 80
        protocol: tcp
    volumes:
      - "matomo:/data"
    env_file:
      - "./matomo.env"
    restart: always

  cron:
    image: crazymax/matomo:latest
    container_name: matomo_cron
    depends_on:
      - matomo
    volumes:
      - "matomo:/data"
    env_file:
      - "./matomo.env"
    environment:
      - "SIDECAR_CRON=1"
      - "CRON_GEOIP=0 2 * * *"
      - "CRON_ARCHIVE=0 * * * *"
      - "ARCHIVE_OPTIONS=--concurrent-requests-per-website=3"
    restart: always

volumes:
  db:
  matomo:
